//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chat.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatCreate")]
  public partial class ReqChatCreate : global::ProtoBuf.IExtensible
  {
    public ReqChatCreate() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _LastTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastTime
    {
      get { return _LastTime; }
      set { _LastTime = value; }
    }
    private string _OnlyStr;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"OnlyStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OnlyStr
    {
      get { return _OnlyStr; }
      set { _OnlyStr = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _UserList = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(5, Name=@"UserList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> UserList
    {
      get { return _UserList; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.ReqChatCreate.NickName> _NickNameList = new global::System.Collections.Generic.List<usercmd.ReqChatCreate.NickName>();
    [global::ProtoBuf.ProtoMember(6, Name=@"NickNameList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.ReqChatCreate.NickName> NickNameList
    {
      get { return _NickNameList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NickName")]
  public partial class NickName : global::ProtoBuf.IExtensible
  {
    public NickName() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatCreate")]
  public partial class RetChatCreate : global::ProtoBuf.IExtensible
  {
    public RetChatCreate() {}
    
    private string _RoomId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _EndTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private string _OnlyStr = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"OnlyStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OnlyStr
    {
      get { return _OnlyStr; }
      set { _OnlyStr = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.RetChatCreate.UserDetail> _UserList = new global::System.Collections.Generic.List<usercmd.RetChatCreate.UserDetail>();
    [global::ProtoBuf.ProtoMember(6, Name=@"UserList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetChatCreate.UserDetail> UserList
    {
      get { return _UserList; }
    }
  
    private ulong _Owner = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Owner
    {
      get { return _Owner; }
      set { _Owner = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserDetail")]
  public partial class UserDetail : global::ProtoBuf.IExtensible
  {
    public UserDetail() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private uint _Sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private uint _Icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _NickName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private uint _VipLevel = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private uint _VipCard = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"VipCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipCard
    {
      get { return _VipCard; }
      set { _VipCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatChangeName")]
  public partial class ReqChatChangeName : global::ProtoBuf.IExtensible
  {
    public ReqChatChangeName() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatReport")]
  public partial class ReqChatReport : global::ProtoBuf.IExtensible
  {
    public ReqChatReport() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _PicUrl;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PicUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PicUrl
    {
      get { return _PicUrl; }
      set { _PicUrl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatReport")]
  public partial class RetChatReport : global::ProtoBuf.IExtensible
  {
    public RetChatReport() {}
    
    private bool _Succ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Succ
    {
      get { return _Succ; }
      set { _Succ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatSet")]
  public partial class ReqChatSet : global::ProtoBuf.IExtensible
  {
    public ReqChatSet() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private bool _IsOpen;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"IsOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOpen
    {
      get { return _IsOpen; }
      set { _IsOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatSet")]
  public partial class RetChatSet : global::ProtoBuf.IExtensible
  {
    public RetChatSet() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private bool _IsOpen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IsOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOpen
    {
      get { return _IsOpen; }
      set { _IsOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatPersonalSet")]
  public partial class ReqChatPersonalSet : global::ProtoBuf.IExtensible
  {
    public ReqChatPersonalSet() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private bool _IsOpen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IsOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOpen
    {
      get { return _IsOpen; }
      set { _IsOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatPersonalSet")]
  public partial class RetChatPersonalSet : global::ProtoBuf.IExtensible
  {
    public RetChatPersonalSet() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private bool _IsOpen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IsOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOpen
    {
      get { return _IsOpen; }
      set { _IsOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatGetRoom")]
  public partial class ReqChatGetRoom : global::ProtoBuf.IExtensible
  {
    public ReqChatGetRoom() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatGetRoom")]
  public partial class RetChatGetRoom : global::ProtoBuf.IExtensible
  {
    public RetChatGetRoom() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _EndTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private string _OnlyStr = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"OnlyStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OnlyStr
    {
      get { return _OnlyStr; }
      set { _OnlyStr = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgChatUser> _UserList = new global::System.Collections.Generic.List<usercmd.MsgChatUser>();
    [global::ProtoBuf.ProtoMember(6, Name=@"UserList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgChatUser> UserList
    {
      get { return _UserList; }
    }
  
    private ulong _Owner = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Owner
    {
      get { return _Owner; }
      set { _Owner = value; }
    }
    private bool _Succ = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Succ
    {
      get { return _Succ; }
      set { _Succ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatDelete")]
  public partial class ReqChatDelete : global::ProtoBuf.IExtensible
  {
    public ReqChatDelete() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatDelete")]
  public partial class RetChatDelete : global::ProtoBuf.IExtensible
  {
    public RetChatDelete() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatUser")]
  public partial class MsgChatUser : global::ProtoBuf.IExtensible
  {
    public MsgChatUser() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private uint _Sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private uint _Icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _NickName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private uint _VipLevel = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private uint _VipCard = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"VipCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipCard
    {
      get { return _VipCard; }
      set { _VipCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatJoin")]
  public partial class ReqChatJoin : global::ProtoBuf.IExtensible
  {
    public ReqChatJoin() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _UserList = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UserList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> UserList
    {
      get { return _UserList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatLeave")]
  public partial class ReqChatLeave : global::ProtoBuf.IExtensible
  {
    public ReqChatLeave() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatTalk")]
  public partial class ReqChatTalk : global::ProtoBuf.IExtensible
  {
    public ReqChatTalk() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatTalk")]
  public partial class RetChatTalk : global::ProtoBuf.IExtensible
  {
    public RetChatTalk() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private uint _Time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatPrivate")]
  public partial class ReqChatPrivate : global::ProtoBuf.IExtensible
  {
    public ReqChatPrivate() {}
    
    private ulong _ToUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ToUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ToUserId
    {
      get { return _ToUserId; }
      set { _ToUserId = value; }
    }
    private ulong _FromUserId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"FromUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong FromUserId
    {
      get { return _FromUserId; }
      set { _FromUserId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private uint _TypeId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserDetail")]
  public partial class UserDetail : global::ProtoBuf.IExtensible
  {
    public UserDetail() {}
    
    private ulong _Id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private uint _Sex = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private uint _Icon = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private uint _State = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatPrivate")]
  public partial class RetChatPrivate : global::ProtoBuf.IExtensible
  {
    public RetChatPrivate() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private uint _Time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private uint _TypeId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    private usercmd.UserDetail _ToDetail = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ToDetail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.UserDetail ToDetail
    {
      get { return _ToDetail; }
      set { _ToDetail = value; }
    }
    private usercmd.UserDetail _FromDetail = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"FromDetail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.UserDetail FromDetail
    {
      get { return _FromDetail; }
      set { _FromDetail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatFansClose")]
  public partial class ReqChatFansClose : global::ProtoBuf.IExtensible
  {
    public ReqChatFansClose() {}
    
    private ulong _ToUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ToUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ToUserId
    {
      get { return _ToUserId; }
      set { _ToUserId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatFansClose")]
  public partial class RetChatFansClose : global::ProtoBuf.IExtensible
  {
    public RetChatFansClose() {}
    
    private bool _Succ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Succ
    {
      get { return _Succ; }
      set { _Succ = value; }
    }
    private ulong _ToUserId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ToUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ToUserId
    {
      get { return _ToUserId; }
      set { _ToUserId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatClose")]
  public partial class RetChatClose : global::ProtoBuf.IExtensible
  {
    public RetChatClose() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatError")]
  public partial class RetChatError : global::ProtoBuf.IExtensible
  {
    public RetChatError() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatKick")]
  public partial class ReqChatKick : global::ProtoBuf.IExtensible
  {
    public ReqChatKick() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _UserIdList = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"UserIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> UserIdList
    {
      get { return _UserIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatFriend")]
  public partial class ReqChatFriend : global::ProtoBuf.IExtensible
  {
    public ReqChatFriend() {}
    
    private ulong _ToUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ToUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ToUserId
    {
      get { return _ToUserId; }
      set { _ToUserId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatSynSet")]
  public partial class MsgChatSynSet : global::ProtoBuf.IExtensible
  {
    public MsgChatSynSet() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private bool _Top;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Top", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Top
    {
      get { return _Top; }
      set { _Top = value; }
    }
    private bool _Disturb;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Disturb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Disturb
    {
      get { return _Disturb; }
      set { _Disturb = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatPersonalSet")]
  public partial class MsgChatPersonalSet : global::ProtoBuf.IExtensible
  {
    public MsgChatPersonalSet() {}
    
    private bool _FriendTalk;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendTalk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool FriendTalk
    {
      get { return _FriendTalk; }
      set { _FriendTalk = value; }
    }
    private bool _QuickTalk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"QuickTalk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool QuickTalk
    {
      get { return _QuickTalk; }
      set { _QuickTalk = value; }
    }
    private bool _BatchPush = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"BatchPush", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool BatchPush
    {
      get { return _BatchPush; }
      set { _BatchPush = value; }
    }
    private bool _UnReadTalk = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UnReadTalk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool UnReadTalk
    {
      get { return _UnReadTalk; }
      set { _UnReadTalk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatTalk")]
  public partial class MsgChatTalk : global::ProtoBuf.IExtensible
  {
    public MsgChatTalk() {}
    
    private string _RoomId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _UserId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgChatTalk.Talk> _Talks = new global::System.Collections.Generic.List<usercmd.MsgChatTalk.Talk>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Talks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgChatTalk.Talk> Talks
    {
      get { return _Talks; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Talk")]
  public partial class Talk : global::ProtoBuf.IExtensible
  {
    public Talk() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private uint _Time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatSyn")]
  public partial class ReqChatSyn : global::ProtoBuf.IExtensible
  {
    public ReqChatSyn() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatSyn")]
  public partial class RetChatSyn : global::ProtoBuf.IExtensible
  {
    public RetChatSyn() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _Rooms = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Rooms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> Rooms
    {
      get { return _Rooms; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgChatTalk> _Talks = new global::System.Collections.Generic.List<usercmd.MsgChatTalk>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Talks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgChatTalk> Talks
    {
      get { return _Talks; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgChatSynSet> _Sets = new global::System.Collections.Generic.List<usercmd.MsgChatSynSet>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Sets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgChatSynSet> Sets
    {
      get { return _Sets; }
    }
  
    private usercmd.MsgChatPersonalSet _PersonalSet;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PersonalSet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgChatPersonalSet PersonalSet
    {
      get { return _PersonalSet; }
      set { _PersonalSet = value; }
    }
    private uint _SendTime = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SendTime
    {
      get { return _SendTime; }
      set { _SendTime = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.UserDetail> _Detail = new global::System.Collections.Generic.List<usercmd.UserDetail>();
    [global::ProtoBuf.ProtoMember(6, Name=@"Detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.UserDetail> Detail
    {
      get { return _Detail; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatPower")]
  public partial class ReqChatPower : global::ProtoBuf.IExtensible
  {
    public ReqChatPower() {}
    
    private ulong _ToUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ToUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ToUserId
    {
      get { return _ToUserId; }
      set { _ToUserId = value; }
    }
    private uint _TypeId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatPower")]
  public partial class RetChatPower : global::ProtoBuf.IExtensible
  {
    public RetChatPower() {}
    
    private bool _Succ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Succ
    {
      get { return _Succ; }
      set { _Succ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatRedSend")]
  public partial class ReqChatRedSend : global::ProtoBuf.IExtensible
  {
    public ReqChatRedSend() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private uint _TypeId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    private uint _Nums;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nums
    {
      get { return _Nums; }
      set { _Nums = value; }
    }
    private uint _Total;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Total
    {
      get { return _Total; }
      set { _Total = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRedDetail")]
  public partial class MsgRedDetail : global::ProtoBuf.IExtensible
  {
    public MsgRedDetail() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private uint _Loves;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Loves", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Loves
    {
      get { return _Loves; }
      set { _Loves = value; }
    }
    private uint _Time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatRedReceive")]
  public partial class ReqChatRedReceive : global::ProtoBuf.IExtensible
  {
    public ReqChatRedReceive() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChatRedSee")]
  public partial class ReqChatRedSee : global::ProtoBuf.IExtensible
  {
    public ReqChatRedSee() {}
    
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetChatRedSee")]
  public partial class RetChatRedSee : global::ProtoBuf.IExtensible
  {
    public RetChatRedSee() {}
    
    private bool _Succ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Succ
    {
      get { return _Succ; }
      set { _Succ = value; }
    }
    private string _RoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _TalkId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TalkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TalkId
    {
      get { return _TalkId; }
      set { _TalkId = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgRedDetail> _Receives = new global::System.Collections.Generic.List<usercmd.MsgRedDetail>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Receives", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgRedDetail> Receives
    {
      get { return _Receives; }
    }
  
    private uint _EndTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatCmd")]
    public enum ChatCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Create", Value=1)]
      Create = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Syn", Value=2)]
      Syn = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Report", Value=3)]
      Report = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Set", Value=4)]
      Set = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PersonalSet", Value=5)]
      PersonalSet = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Friend", Value=6)]
      Friend = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Private", Value=7)]
      Private = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Power", Value=8)]
      Power = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Close", Value=9)]
      Close = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=10)]
      Error = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FansClose", Value=21)]
      FansClose = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WorldChat", Value=22)]
      WorldChat = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamChat", Value=23)]
      TeamChat = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Delete", Value=11)]
      Delete = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Join", Value=12)]
      Join = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Leave", Value=13)]
      Leave = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Talk", Value=14)]
      Talk = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Kick", Value=15)]
      Kick = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoom", Value=16)]
      GetRoom = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeName", Value=17)]
      ChangeName = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedSend", Value=18)]
      RedSend = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedReceive", Value=19)]
      RedReceive = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedSee", Value=20)]
      RedSee = 20
    }
  
}