//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sns.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetPhotoList")]
  public partial class RetPhotoList : global::ProtoBuf.IExtensible
  {
    public RetPhotoList() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetPhotoList.PhotoInfo> _Data = new global::System.Collections.Generic.List<usercmd.RetPhotoList.PhotoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetPhotoList.PhotoInfo> Data
    {
      get { return _Data; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhotoInfo")]
  public partial class PhotoInfo : global::ProtoBuf.IExtensible
  {
    public PhotoInfo() {}
    
    private string _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private ulong _Uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private uint _FileSize;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"FileSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FileSize
    {
      get { return _FileSize; }
      set { _FileSize = value; }
    }
    private string _UploadUrl;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UploadUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UploadUrl
    {
      get { return _UploadUrl; }
      set { _UploadUrl = value; }
    }
    private uint _ShowNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ShowNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ShowNum
    {
      get { return _ShowNum; }
      set { _ShowNum = value; }
    }
    private uint _LaudNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"LaudNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LaudNum
    {
      get { return _LaudNum; }
      set { _LaudNum = value; }
    }
    private string _Thumb198;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Thumb198", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Thumb198
    {
      get { return _Thumb198; }
      set { _Thumb198 = value; }
    }
    private ulong _Time;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private uint _State;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint State
    {
      get { return _State; }
      set { _State = value; }
    }
    private bool _IsPraise = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"IsPraise", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsPraise
    {
      get { return _IsPraise; }
      set { _IsPraise = value; }
    }
    private bool _IsShow = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"IsShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsShow
    {
      get { return _IsShow; }
      set { _IsShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetSnsDetailInfo")]
  public partial class RetSnsDetailInfo : global::ProtoBuf.IExtensible
  {
    public RetSnsDetailInfo() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _NickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private uint _Icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private uint _Location;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Location
    {
      get { return _Location; }
      set { _Location = value; }
    }
    private string _Sign;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Sign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sign
    {
      get { return _Sign; }
      set { _Sign = value; }
    }
    private uint _Sex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Scores;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Scores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Scores
    {
      get { return _Scores; }
      set { _Scores = value; }
    }
    private uint _FollowNum = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"FollowNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint FollowNum
    {
      get { return _FollowNum; }
      set { _FollowNum = value; }
    }
    private uint _FansNum = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"FansNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint FansNum
    {
      get { return _FansNum; }
      set { _FansNum = value; }
    }
    private uint _FriendNum = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"FriendNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint FriendNum
    {
      get { return _FriendNum; }
      set { _FriendNum = value; }
    }
    private bool _ShowPos = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ShowPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ShowPos
    {
      get { return _ShowPos; }
      set { _ShowPos = value; }
    }
    private uint _Age = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Age
    {
      get { return _Age; }
      set { _Age = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private uint _AudienceNum = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"AudienceNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AudienceNum
    {
      get { return _AudienceNum; }
      set { _AudienceNum = value; }
    }
    private string _AudienceUrl = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"AudienceUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AudienceUrl
    {
      get { return _AudienceUrl; }
      set { _AudienceUrl = value; }
    }
    private uint _AudienceTime = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"AudienceTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AudienceTime
    {
      get { return _AudienceTime; }
      set { _AudienceTime = value; }
    }
    private bool _IsFollow = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"IsFollow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsFollow
    {
      get { return _IsFollow; }
      set { _IsFollow = value; }
    }
    private bool _IsBanList = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"IsBanList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsBanList
    {
      get { return _IsBanList; }
      set { _IsBanList = value; }
    }
    private uint _State = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint State
    {
      get { return _State; }
      set { _State = value; }
    }
    private string _Position = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private uint _AniElephant = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"AniElephant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniElephant
    {
      get { return _AniElephant; }
      set { _AniElephant = value; }
    }
    private uint _AniPanda = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"AniPanda", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniPanda
    {
      get { return _AniPanda; }
      set { _AniPanda = value; }
    }
    private uint _AniWhale = default(uint);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"AniWhale", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniWhale
    {
      get { return _AniWhale; }
      set { _AniWhale = value; }
    }
    private uint _AniMermaid = default(uint);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"AniMermaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniMermaid
    {
      get { return _AniMermaid; }
      set { _AniMermaid = value; }
    }
    private uint _AniEagle = default(uint);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"AniEagle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniEagle
    {
      get { return _AniEagle; }
      set { _AniEagle = value; }
    }
    private uint _AniPhoenix = default(uint);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"AniPhoenix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniPhoenix
    {
      get { return _AniPhoenix; }
      set { _AniPhoenix = value; }
    }
    private uint _AniScorpio = default(uint);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"AniScorpio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniScorpio
    {
      get { return _AniScorpio; }
      set { _AniScorpio = value; }
    }
    private uint _AniSpider = default(uint);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"AniSpider", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniSpider
    {
      get { return _AniSpider; }
      set { _AniSpider = value; }
    }
    private uint _HighFree1001 = default(uint);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"HighFree1001", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighFree1001
    {
      get { return _HighFree1001; }
      set { _HighFree1001 = value; }
    }
    private uint _HighFree1003 = default(uint);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"HighFree1003", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighFree1003
    {
      get { return _HighFree1003; }
      set { _HighFree1003 = value; }
    }
    private uint _HighQuick1002 = default(uint);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"HighQuick1002", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighQuick1002
    {
      get { return _HighQuick1002; }
      set { _HighQuick1002 = value; }
    }
    private uint _HighQuick1004 = default(uint);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"HighQuick1004", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighQuick1004
    {
      get { return _HighQuick1004; }
      set { _HighQuick1004 = value; }
    }
    private uint _HighSky1005 = default(uint);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"HighSky1005", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighSky1005
    {
      get { return _HighSky1005; }
      set { _HighSky1005 = value; }
    }
    private uint _HighSky1006 = default(uint);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"HighSky1006", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighSky1006
    {
      get { return _HighSky1006; }
      set { _HighSky1006 = value; }
    }
    private uint _HighCross1007 = default(uint);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"HighCross1007", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighCross1007
    {
      get { return _HighCross1007; }
      set { _HighCross1007 = value; }
    }
    private uint _HighCross1008 = default(uint);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"HighCross1008", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighCross1008
    {
      get { return _HighCross1008; }
      set { _HighCross1008 = value; }
    }
    private uint _HighInsect1009 = default(uint);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"HighInsect1009", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighInsect1009
    {
      get { return _HighInsect1009; }
      set { _HighInsect1009 = value; }
    }
    private uint _HighInsect1010 = default(uint);
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"HighInsect1010", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighInsect1010
    {
      get { return _HighInsect1010; }
      set { _HighInsect1010 = value; }
    }
    private uint _HighLive1201 = default(uint);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"HighLive1201", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HighLive1201
    {
      get { return _HighLive1201; }
      set { _HighLive1201 = value; }
    }
    private uint _AniQiLin = default(uint);
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"AniQiLin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AniQiLin
    {
      get { return _AniQiLin; }
      set { _AniQiLin = value; }
    }
    private uint _NineSnake = default(uint);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"NineSnake", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NineSnake
    {
      get { return _NineSnake; }
      set { _NineSnake = value; }
    }
    private uint _Dragon = default(uint);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"Dragon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Dragon
    {
      get { return _Dragon; }
      set { _Dragon = value; }
    }
    private uint _XuKong = default(uint);
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"XuKong", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint XuKong
    {
      get { return _XuKong; }
      set { _XuKong = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetMatchList")]
  public partial class RetMatchList : global::ProtoBuf.IExtensible
  {
    public RetMatchList() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetMatchList.MatchData> _Datas = new global::System.Collections.Generic.List<usercmd.RetMatchList.MatchData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetMatchList.MatchData> Datas
    {
      get { return _Datas; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchData")]
  public partial class MatchData : global::ProtoBuf.IExtensible
  {
    public MatchData() {}
    
    private uint _Icon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _NickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private uint _Time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private uint _Rank;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Rank
    {
      get { return _Rank; }
      set { _Rank = value; }
    }
    private uint _SceneID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SceneID
    {
      get { return _SceneID; }
      set { _SceneID = value; }
    }
    private uint _Score;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private uint _AnimalID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"AnimalID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AnimalID
    {
      get { return _AnimalID; }
      set { _AnimalID = value; }
    }
    private uint _JiangGuo;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"JiangGuo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JiangGuo
    {
      get { return _JiangGuo; }
      set { _JiangGuo = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetHonorList")]
  public partial class RetHonorList : global::ProtoBuf.IExtensible
  {
    public RetHonorList() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetHonorList.HonorUser> _Honors = new global::System.Collections.Generic.List<usercmd.RetHonorList.HonorUser>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Honors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetHonorList.HonorUser> Honors
    {
      get { return _Honors; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HonorUser")]
  public partial class HonorUser : global::ProtoBuf.IExtensible
  {
    public HonorUser() {}
    
    private uint _Season;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Season", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Season
    {
      get { return _Season; }
      set { _Season = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Scores;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Scores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Scores
    {
      get { return _Scores; }
      set { _Scores = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetUserBaseInfo")]
  public partial class RetUserBaseInfo : global::ProtoBuf.IExtensible
  {
    public RetUserBaseInfo() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private uint _Icon = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private uint _Sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private uint _Age = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Age
    {
      get { return _Age; }
      set { _Age = value; }
    }
    private uint _Location = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Location
    {
      get { return _Location; }
      set { _Location = value; }
    }
    private string _Position = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private uint _RelType = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"RelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RelType
    {
      get { return _RelType; }
      set { _RelType = value; }
    }
    private uint _Level = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Scores = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Scores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Scores
    {
      get { return _Scores; }
      set { _Scores = value; }
    }
    private uint _VipLevel = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private uint _VipCard = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"VipCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint VipCard
    {
      get { return _VipCard; }
      set { _VipCard = value; }
    }
    private ulong _CorpId = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"CorpId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CorpId
    {
      get { return _CorpId; }
      set { _CorpId = value; }
    }
    private string _CorpName = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"CorpName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CorpName
    {
      get { return _CorpName; }
      set { _CorpName = value; }
    }
    private uint _CorpLevel = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"CorpLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CorpLevel
    {
      get { return _CorpLevel; }
      set { _CorpLevel = value; }
    }
    private uint _CorpCLogo = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"CorpCLogo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CorpCLogo
    {
      get { return _CorpCLogo; }
      set { _CorpCLogo = value; }
    }
    private string _CorpLogo = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"CorpLogo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CorpLogo
    {
      get { return _CorpLogo; }
      set { _CorpLogo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsReportMsg")]
  public partial class IsReportMsg : global::ProtoBuf.IExtensible
  {
    public IsReportMsg() {}
    
    private bool _Ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Ret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Ret
    {
      get { return _Ret; }
      set { _Ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetReportMsgList")]
  public partial class RetReportMsgList : global::ProtoBuf.IExtensible
  {
    public RetReportMsgList() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetReportMsgList.ReportMsg> _Data = new global::System.Collections.Generic.List<usercmd.RetReportMsgList.ReportMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetReportMsgList.ReportMsg> Data
    {
      get { return _Data; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportMsg")]
  public partial class ReportMsg : global::ProtoBuf.IExtensible
  {
    public ReportMsg() {}
    
    private uint _RClass;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RClass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RClass
    {
      get { return _RClass; }
      set { _RClass = value; }
    }
    private uint _Rtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Rtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Rtype
    {
      get { return _Rtype; }
      set { _Rtype = value; }
    }
    private string _RId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RId
    {
      get { return _RId; }
      set { _RId = value; }
    }
    private string _Reason = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
    private long _Time = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}