//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: wilds.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDoNothing")]
  public partial class MsgDoNothing : global::ProtoBuf.IExtensible
  {
    public MsgDoNothing() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _hello = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hello", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hello
    {
      get { return _hello; }
      set { _hello = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BanBarrageMsg")]
  public partial class BanBarrageMsg : global::ProtoBuf.IExtensible
  {
    public BanBarrageMsg() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private uint _Params = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Params
    {
      get { return _Params; }
      set { _Params = value; }
    }
    private string _JsonParam = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"JsonParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string JsonParam
    {
      get { return _JsonParam; }
      set { _JsonParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLogin")]
  public partial class MsgLogin : global::ProtoBuf.IExtensible
  {
    public MsgLogin() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetErrorMsgCmd")]
  public partial class RetErrorMsgCmd : global::ProtoBuf.IExtensible
  {
    public RetErrorMsgCmd() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private uint _Params = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Params
    {
      get { return _Params; }
      set { _Params = value; }
    }
    private string _JsonParam = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"JsonParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string JsonParam
    {
      get { return _JsonParam; }
      set { _JsonParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoginResult")]
  public partial class MsgLoginResult : global::ProtoBuf.IExtensible
  {
    public MsgLoginResult() {}
    
    private bool _ok;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ok
    {
      get { return _ok; }
      set { _ok = value; }
    }
    private ulong _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayer> _others = new global::System.Collections.Generic.List<usercmd.MsgPlayer>();
    [global::ProtoBuf.ProtoMember(4, Name=@"others", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayer> others
    {
      get { return _others; }
    }
  
    private uint _frame;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private uint _Local;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Local", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Local
    {
      get { return _Local; }
      set { _Local = value; }
    }
    private string _RoomName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"RoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoomName
    {
      get { return _RoomName; }
      set { _RoomName = value; }
    }
    private uint _ballId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ballId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ballId
    {
      get { return _ballId; }
      set { _ballId = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgBall> _balls = new global::System.Collections.Generic.List<usercmd.MsgBall>();
    [global::ProtoBuf.ProtoMember(9, Name=@"balls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgBall> balls
    {
      get { return _balls; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayerBall> _playerballs = new global::System.Collections.Generic.List<usercmd.MsgPlayerBall>();
    [global::ProtoBuf.ProtoMember(10, Name=@"playerballs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayerBall> playerballs
    {
      get { return _playerballs; }
    }
  
    private uint _TeamName = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"TeamName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamName
    {
      get { return _TeamName; }
      set { _TeamName = value; }
    }
    private uint _TeamId = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"TeamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamId
    {
      get { return _TeamId; }
      set { _TeamId = value; }
    }
    private uint _TeamNoticeCD = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"TeamNoticeCD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamNoticeCD
    {
      get { return _TeamNoticeCD; }
      set { _TeamNoticeCD = value; }
    }
    private uint _leftTime = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"leftTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint leftTime
    {
      get { return _leftTime; }
      set { _leftTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTop")]
  public partial class MsgTop : global::ProtoBuf.IExtensible
  {
    public MsgTop() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayer> _players = new global::System.Collections.Generic.List<usercmd.MsgPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayer> players
    {
      get { return _players; }
    }
  
    private uint _EndTime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private uint _Rank = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Rank
    {
      get { return _Rank; }
      set { _Rank = value; }
    }
    private uint _KillNum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"KillNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint KillNum
    {
      get { return _KillNum; }
      set { _KillNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneTCP")]
  public partial class MsgSceneTCP : global::ProtoBuf.IExtensible
  {
    public MsgSceneTCP() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.BallEat> _eats = new global::System.Collections.Generic.List<usercmd.BallEat>();
    [global::ProtoBuf.ProtoMember(1, Name=@"eats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.BallEat> eats
    {
      get { return _eats; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgBall> _adds = new global::System.Collections.Generic.List<usercmd.MsgBall>();
    [global::ProtoBuf.ProtoMember(2, Name=@"adds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgBall> adds
    {
      get { return _adds; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _removes = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"removes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> removes
    {
      get { return _removes; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.HitMsg> _hits = new global::System.Collections.Generic.List<usercmd.HitMsg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"hits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.HitMsg> hits
    {
      get { return _hits; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayerBall> _addPlayers = new global::System.Collections.Generic.List<usercmd.MsgPlayerBall>();
    [global::ProtoBuf.ProtoMember(5, Name=@"addPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayerBall> addPlayers
    {
      get { return _addPlayers; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _removePlayers = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"removePlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> removePlayers
    {
      get { return _removePlayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneUDP")]
  public partial class MsgSceneUDP : global::ProtoBuf.IExtensible
  {
    public MsgSceneUDP() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.BallMove> _moves = new global::System.Collections.Generic.List<usercmd.BallMove>();
    [global::ProtoBuf.ProtoMember(1, Name=@"moves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.BallMove> moves
    {
      get { return _moves; }
    }
  
    private uint _frame;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBindTCPSession")]
  public partial class MsgBindTCPSession : global::ProtoBuf.IExtensible
  {
    public MsgBindTCPSession() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayer")]
  public partial class MsgPlayer : global::ProtoBuf.IExtensible
  {
    public MsgPlayer() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _local = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"local", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint local
    {
      get { return _local; }
      set { _local = value; }
    }
    private bool _IsLive = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IsLive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsLive
    {
      get { return _IsLive; }
      set { _IsLive = value; }
    }
    private usercmd.MsgPlayerSnap _SnapInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SnapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.MsgPlayerSnap SnapInfo
    {
      get { return _SnapInfo; }
      set { _SnapInfo = value; }
    }
    private uint _ballId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ballId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ballId
    {
      get { return _ballId; }
      set { _ballId = value; }
    }
    private uint _curexp = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"curexp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curexp
    {
      get { return _curexp; }
      set { _curexp = value; }
    }
    private uint _curmp = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"curmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curmp
    {
      get { return _curmp; }
      set { _curmp = value; }
    }
    private uint _animalid = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"animalid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint animalid
    {
      get { return _animalid; }
      set { _animalid = value; }
    }
    private uint _curhp = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"curhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curhp
    {
      get { return _curhp; }
      set { _curhp = value; }
    }
    private uint _TeamName = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"TeamName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamName
    {
      get { return _TeamName; }
      set { _TeamName = value; }
    }
    private int _bombNum = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bombNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bombNum
    {
      get { return _bombNum; }
      set { _bombNum = value; }
    }
    private int _hammerNum = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"hammerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hammerNum
    {
      get { return _hammerNum; }
      set { _hammerNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAddPlayer")]
  public partial class MsgAddPlayer : global::ProtoBuf.IExtensible
  {
    public MsgAddPlayer() {}
    
    private usercmd.MsgPlayer _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRefreshPlayer")]
  public partial class MsgRefreshPlayer : global::ProtoBuf.IExtensible
  {
    public MsgRefreshPlayer() {}
    
    private usercmd.MsgPlayer _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAsyncPlayerAnimal")]
  public partial class MsgAsyncPlayerAnimal : global::ProtoBuf.IExtensible
  {
    public MsgAsyncPlayerAnimal() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _animalid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"animalid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint animalid
    {
      get { return _animalid; }
      set { _animalid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRemovePlayer")]
  public partial class MsgRemovePlayer : global::ProtoBuf.IExtensible
  {
    public MsgRemovePlayer() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMove")]
  public partial class MsgMove : global::ProtoBuf.IExtensible
  {
    public MsgMove() {}
    
    private int _angle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private int _power;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRelife")]
  public partial class MsgRelife : global::ProtoBuf.IExtensible
  {
    public MsgRelife() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgS2CRelife")]
  public partial class MsgS2CRelife : global::ProtoBuf.IExtensible
  {
    public MsgS2CRelife() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _frame = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private usercmd.MsgPlayerSnap _SnapInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SnapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayerSnap SnapInfo
    {
      get { return _SnapInfo; }
      set { _SnapInfo = value; }
    }
    private uint _curhp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curhp
    {
      get { return _curhp; }
      set { _curhp = value; }
    }
    private uint _curmp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"curmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curmp
    {
      get { return _curmp; }
      set { _curmp = value; }
    }
    private uint _animalid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"animalid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint animalid
    {
      get { return _animalid; }
      set { _animalid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDeath")]
  public partial class MsgDeath : global::ProtoBuf.IExtensible
  {
    public MsgDeath() {}
    
    private uint _maxScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxScore
    {
      get { return _maxScore; }
      set { _maxScore = value; }
    }
    private ulong _killId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"killId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong killId
    {
      get { return _killId; }
      set { _killId = value; }
    }
    private string _killName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"killName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string killName
    {
      get { return _killName; }
      set { _killName = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private uint _animalid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"animalid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint animalid
    {
      get { return _animalid; }
      set { _animalid = value; }
    }
    private uint _killanimalid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"killanimalid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint killanimalid
    {
      get { return _killanimalid; }
      set { _killanimalid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndPlayer")]
  public partial class EndPlayer : global::ProtoBuf.IExtensible
  {
    public EndPlayer() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _UName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UName
    {
      get { return _UName; }
      set { _UName = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private ulong _Score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private uint _KillNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"KillNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint KillNum
    {
      get { return _KillNum; }
      set { _KillNum = value; }
    }
    private uint _Sex = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private uint _Icon = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private uint _Location = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Location
    {
      get { return _Location; }
      set { _Location = value; }
    }
    private uint _Money = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private uint _Rank = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Rank
    {
      get { return _Rank; }
      set { _Rank = value; }
    }
    private string _PassIcon = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private bool _IsMvp = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"IsMvp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsMvp
    {
      get { return _IsMvp; }
      set { _IsMvp = value; }
    }
    private bool _IsFollow = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"IsFollow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsFollow
    {
      get { return _IsFollow; }
      set { _IsFollow = value; }
    }
    private int _AddMoney = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"AddMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AddMoney
    {
      get { return _AddMoney; }
      set { _AddMoney = value; }
    }
    private uint _AnimalId = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"AnimalId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint AnimalId
    {
      get { return _AnimalId; }
      set { _AnimalId = value; }
    }
    private uint _TeamScore = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"TeamScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamScore
    {
      get { return _TeamScore; }
      set { _TeamScore = value; }
    }
    private uint _TeamName = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"TeamName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TeamName
    {
      get { return _TeamName; }
      set { _TeamName = value; }
    }
    private ulong _LeaderId = default(ulong);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"LeaderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong LeaderId
    {
      get { return _LeaderId; }
      set { _LeaderId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Anchor")]
  public partial class Anchor : global::ProtoBuf.IExtensible
  {
    public Anchor() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEndRoom")]
  public partial class MsgEndRoom : global::ProtoBuf.IExtensible
  {
    public MsgEndRoom() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.EndPlayer> _players = new global::System.Collections.Generic.List<usercmd.EndPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.EndPlayer> players
    {
      get { return _players; }
    }
  
    private usercmd.EndPlayer _UserSelf = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserSelf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.EndPlayer UserSelf
    {
      get { return _UserSelf; }
      set { _UserSelf = value; }
    }
    private ulong _LeaderId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LeaderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong LeaderId
    {
      get { return _LeaderId; }
      set { _LeaderId = value; }
    }
    private uint _OldLevel = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OldLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OldLevel
    {
      get { return _OldLevel; }
      set { _OldLevel = value; }
    }
    private uint _OldScores = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"OldScores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint OldScores
    {
      get { return _OldScores; }
      set { _OldScores = value; }
    }
    private uint _Level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Scores = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Scores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Scores
    {
      get { return _Scores; }
      set { _Scores = value; }
    }
    private bool _IsValid = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"IsValid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsValid
    {
      get { return _IsValid; }
      set { _IsValid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientHeartBeat")]
  public partial class ClientHeartBeat : global::ProtoBuf.IExtensible
  {
    public ClientHeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCastSkill")]
  public partial class MsgCastSkill : global::ProtoBuf.IExtensible
  {
    public MsgCastSkill() {}
    
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetVoiceInfo")]
  public partial class RetVoiceInfo : global::ProtoBuf.IExtensible
  {
    public RetVoiceInfo() {}
    
    private string _Address;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private uint _RoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqToSpeak")]
  public partial class ReqToSpeak : global::ProtoBuf.IExtensible
  {
    public ReqToSpeak() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetToSpeak")]
  public partial class RetToSpeak : global::ProtoBuf.IExtensible
  {
    public RetToSpeak() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private uint _Money = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private uint _Time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetSpeakUser")]
  public partial class RetSpeakUser : global::ProtoBuf.IExtensible
  {
    public RetSpeakUser() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _NeedTm;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"NeedTm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NeedTm
    {
      get { return _NeedTm; }
      set { _NeedTm = value; }
    }
    private uint _TotalTm;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TotalTm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalTm
    {
      get { return _TotalTm; }
      set { _TotalTm = value; }
    }
    private uint _IsBaned = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"IsBaned", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint IsBaned
    {
      get { return _IsBaned; }
      set { _IsBaned = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetTeamRankList")]
  public partial class RetTeamRankList : global::ProtoBuf.IExtensible
  {
    public RetTeamRankList() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetTeamRankList.TeamRank> _Teams = new global::System.Collections.Generic.List<usercmd.RetTeamRankList.TeamRank>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Teams", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetTeamRankList.TeamRank> Teams
    {
      get { return _Teams; }
    }
  
    private uint _WatchNum = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"WatchNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint WatchNum
    {
      get { return _WatchNum; }
      set { _WatchNum = value; }
    }
    private uint _EndTime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private uint _killNum = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"killNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint killNum
    {
      get { return _killNum; }
      set { _killNum = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamRank")]
  public partial class TeamRank : global::ProtoBuf.IExtensible
  {
    public TeamRank() {}
    
    private uint _Tname = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Tname", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Tname
    {
      get { return _Tname; }
      set { _Tname = value; }
    }
    private uint _Num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private double _Score = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private int _LastRank = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"LastRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LastRank
    {
      get { return _LastRank; }
      set { _LastRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetTeamMemPos")]
  public partial class RetTeamMemPos : global::ProtoBuf.IExtensible
  {
    public RetTeamMemPos() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RetTeamMemPos.MemPos> _Mems = new global::System.Collections.Generic.List<usercmd.RetTeamMemPos.MemPos>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Mems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RetTeamMemPos.MemPos> Mems
    {
      get { return _Mems; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemPos")]
  public partial class MemPos : global::ProtoBuf.IExtensible
  {
    public MemPos() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _X;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int X
    {
      get { return _X; }
      set { _X = value; }
    }
    private int _Y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPlayerState")]
  public partial class ReqPlayerState : global::ProtoBuf.IExtensible
  {
    public ReqPlayerState() {}
    
    private uint _State;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetPlayerState")]
  public partial class RetPlayerState : global::ProtoBuf.IExtensible
  {
    public RetPlayerState() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private uint _State;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint State
    {
      get { return _State; }
      set { _State = value; }
    }
    private uint _LTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LTime
    {
      get { return _LTime; }
      set { _LTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetAddComment")]
  public partial class RetAddComment : global::ProtoBuf.IExtensible
  {
    public RetAddComment() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetBeJoined")]
  public partial class RetBeJoined : global::ProtoBuf.IExtensible
  {
    public RetBeJoined() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRun")]
  public partial class MsgRun : global::ProtoBuf.IExtensible
  {
    public MsgRun() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneChat")]
  public partial class MsgSceneChat : global::ProtoBuf.IExtensible
  {
    public MsgSceneChat() {}
    
    private string _Msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Msg
    {
      get { return _Msg; }
      set { _Msg = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgS2CSceneChat")]
  public partial class MsgS2CSceneChat : global::ProtoBuf.IExtensible
  {
    public MsgS2CSceneChat() {}
    
    private string _Msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Msg
    {
      get { return _Msg; }
      set { _Msg = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerSnap")]
  public partial class MsgPlayerSnap : global::ProtoBuf.IExtensible
  {
    public MsgPlayerSnap() {}
    
    private float _Snapx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Snapx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Snapx
    {
      get { return _Snapx; }
      set { _Snapx = value; }
    }
    private float _Snapy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Snapy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Snapy
    {
      get { return _Snapy; }
      set { _Snapy = value; }
    }
    private float _Angle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Angle
    {
      get { return _Angle; }
      set { _Angle = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBall")]
  public partial class MsgBall : global::ProtoBuf.IExtensible
  {
    public MsgBall() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerBall")]
  public partial class MsgPlayerBall : global::ProtoBuf.IExtensible
  {
    public MsgPlayerBall() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _mp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _angle = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BallMove")]
  public partial class BallMove : global::ProtoBuf.IExtensible
  {
    public BallMove() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _angle = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BallEat")]
  public partial class BallEat : global::ProtoBuf.IExtensible
  {
    public BallEat() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private uint _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HitMsg")]
  public partial class HitMsg : global::ProtoBuf.IExtensible
  {
    public HitMsg() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private uint _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _addHp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"addHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addHp
    {
      get { return _addHp; }
      set { _addHp = value; }
    }
    private uint _curHp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curHp
    {
      get { return _curHp; }
      set { _curHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTeamInfoMsg")]
  public partial class UpdateTeamInfoMsg : global::ProtoBuf.IExtensible
  {
    public UpdateTeamInfoMsg() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.TeamInfoMsg> _members = new global::System.Collections.Generic.List<usercmd.TeamInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.TeamInfoMsg> members
    {
      get { return _members; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.TeamInfoMsg> _topPlayers = new global::System.Collections.Generic.List<usercmd.TeamInfoMsg>();
    [global::ProtoBuf.ProtoMember(2, Name=@"topPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.TeamInfoMsg> topPlayers
    {
      get { return _topPlayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamInfoMsg")]
  public partial class TeamInfoMsg : global::ProtoBuf.IExtensible
  {
    public TeamInfoMsg() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamNoticeMsg")]
  public partial class TeamNoticeMsg : global::ProtoBuf.IExtensible
  {
    public TeamNoticeMsg() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgTypeCmd")]
    public enum MsgTypeCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1)]
      Login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Top", Value=2)]
      Top = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPlayer", Value=3)]
      AddPlayer = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemovePlayer", Value=4)]
      RemovePlayer = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Move", Value=6)]
      Move = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Run", Value=7)]
      Run = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReLife", Value=9)]
      ReLife = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Death", Value=10)]
      Death = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndRoom", Value=11)]
      EndRoom = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPlayer", Value=13)]
      RefreshPlayer = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AsyncPlayerAnimal", Value=14)]
      AsyncPlayerAnimal = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartBeat", Value=16)]
      HeartBeat = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneChat", Value=20)]
      SceneChat = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActCloseSocket", Value=21)]
      ActCloseSocket = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMsg", Value=25)]
      ErrorMsg = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneTCP", Value=31)]
      SceneTCP = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneUDP", Value=32)]
      SceneUDP = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BindTCPSession", Value=33)]
      BindTCPSession = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamRankList", Value=40)]
      TeamRankList = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamMemPos", Value=41)]
      TeamMemPos = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamNotice", Value=42)]
      TeamNotice = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CastSkill", Value=50)]
      CastSkill = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndQRoom", Value=65)]
      EndQRoom = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VoiceInfo", Value=36)]
      VoiceInfo = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ToSpeak", Value=37)]
      ToSpeak = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpeakUser", Value=38)]
      SpeakUser = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateTeamInfo", Value=77)]
      UpdateTeamInfo = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerAnchor", Value=504)]
      PlayerAnchor = 504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerUnAnchor", Value=505)]
      PlayerUnAnchor = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetPlayerList", Value=507)]
      GetPlayerList = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DoNothing", Value=701)]
      DoNothing = 701
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SystemMsgType")]
    public enum SystemMsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMNone", Value=0)]
      SMNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMKilled", Value=1)]
      SMKilled = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMEat", Value=2)]
      SMEat = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMEat1", Value=3)]
      SMEat1 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMBreak", Value=4)]
      SMBreak = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMFirst", Value=5)]
      SMFirst = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMInTop", Value=6)]
      SMInTop = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMBeBreak", Value=7)]
      SMBeBreak = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MapObjectConfigType")]
    public enum MapObjectConfigType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Empty", Value=0)]
      Empty = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Block", Value=1)]
      Block = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BallType")]
    public enum BallType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Player", Value=1)]
      Player = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodBegin", Value=10)]
      FoodBegin = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodNormal", Value=11)]
      FoodNormal = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodHammer", Value=12)]
      FoodHammer = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodBomb", Value=13)]
      FoodBomb = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodEnd", Value=19)]
      FoodEnd = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedBegin", Value=20)]
      FeedBegin = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedNormal", Value=21)]
      FeedNormal = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedEnd", Value=29)]
      FeedEnd = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillBegin", Value=30)]
      SkillBegin = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillHammer", Value=31)]
      SkillHammer = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillBomb", Value=32)]
      SkillBomb = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillEnd", Value=39)]
      SkillEnd = 39
    }
  
}